### ISSUE TITLE
`intl` cannot be build on Alpine & PHP 7.2

### ISSUE THREAD

**Issue by mvorisek** [mlocati/docker-php-extension-installer#553]
### Version of install-php-extensions

latest

### Error description

see https://github.com/mvorisek/image-php/runs/5755017479?check_suite_focus=true#step:5:5916

```
 /usr/src/php/ext/intl/collator/collator_sort.c: In function 'zif_collator_sort':
/usr/src/php/ext/intl/collator/collator_sort.c:349:26: error: 'TRUE' undeclared (first use in this function)
  349 |  collator_sort_internal( TRUE, INTERNAL_FUNCTION_PARAM_PASSTHRU );
      |                          ^~~~
/usr/src/php/ext/intl/collator/collator_sort.c:349:26: note: each undeclared identifier is reported only once for each function it appears in
/usr/src/php/ext/intl/collator/collator_sort.c: In function 'zif_collator_asort':
/usr/src/php/ext/intl/collator/collator_sort.c:543:26: error: 'FALSE' undeclared (first use in this function)
  543 |  collator_sort_internal( FALSE, INTERNAL_FUNCTION_PARAM_PASSTHRU );
      |                          ^~~~~
make: *** [Makefile:204: collator/collator_sort.lo] Error 1
```

### Docker image

Alpine & PHP 7.2

**Comment by mlocati** [comment]
I can't replicate it: see https://github.com/mlocati/docker-php-extension-installer/pull/557/checks

**Comment by mvorisek** [comment]
my setup is running on Alpine 3.15, for PHP 7.2, I belive there is no official Docker image to test

**Comment by mvorisek** [comment]
so please test with (official) `7.4.12-cli` Docker image

**Comment by mlocati** [comment]
> so please test with (official) `7.4.12-cli` Docker image

```
$ docker run --rm -it -e CI=true -v path/to/docker-php-extension-installer:/app php:7.4.12-cli bash -c "/app/install-php-extensions intl && php --ri intl"

install-php-extensions v.master

[...omissis...]

npacking libicu-dev:amd64 (63.1-6+deb10u3) ...
Setting up libicu63:amd64 (63.1-6+deb10u3) ...
Setting up icu-devtools (63.1-6+deb10u3) ...
Setting up libicu-dev:amd64 (63.1-6+deb10u3) ...

[...omissis...]

### INSTALLING BUNDLED MODULE intl ###

[...omissis...]

intl

Internationalization support => enabled
ICU version => 63.1
ICU Data version => 63.1
ICU TZData version => 2018e
ICU Unicode version => 11.0

Directive => Local Value => Master Value
intl.default_locale => no value => no value
intl.error_level => 0 => 0
intl.use_exceptions => 0 => 0
```

**Comment by mvorisek** [comment]
I see, the tag uses Alpine 3.12 instead of the latest one.

I will put a post repro Dockerfile soon.

**Comment by mvorisek** [comment]
issue should be reproducible with `ghcr.io/mvorisek/image-php:7.2-alpine-base--for-intl-dev` image, please rerun this test command:

```
$ docker run --rm -it -e CI=true -v path/to/docker-php-extension-installer:/app ghcr.io/mvorisek/image-php:7.2-alpine-base--for-intl-dev bash -c "/app/install-php-extensions intl && php --ri intl"
```

**Comment by mlocati** [comment]
I'm sorry, but I'm not going to support custom docker PHP images (supporting the official ones is already rather complex).

Of course, you can patch the PHP source code yourself.
Here's a sample script that you can use to apply https://github.com/php/php-src/pull/6397:

```sh
# Install the required apk packages
apk -u add patch

# Extract the PHP source code
docker-php-source extract

# Patch the PHP source code
patch /usr/src/php/acinclude.m4 <<'EOF'
@@ -2274,6 +2274,8 @@
       ICU_CXXFLAGS="$ICU_CXXFLAGS -DU_USING_ICU_NAMESPACE=1"
     fi
   fi
+
+  ICU_CFLAGS="$ICU_CFLAGS -DU_DEFINE_FALSE_AND_TRUE=1"
 ])

 dnl
EOF
```

Then simply run install-php-extensions as usual,

I tested this code, and it seems to throw the same error even if the patch is actually applied. Maybe you'll need to rebuild the configure script with the `autoconf` command? But again, that's up to you :wink:

**Comment by mvorisek** [comment]
I was thinking about applying such patch by this installer for all PHP 7.2 (and lower) versions.

Thanks, I already have setup for full build from source, so patching it from my side is easy.

**Comment by mvorisek** [comment]
`ICU_CFLAGS="$ICU_CFLAGS -DU_DEFINE_FALSE_AND_TRUE=1"` patch did NOT fixed the issue on Alpine 3.15

here is a working patch: https://github.com/mvorisek/image-php/blob/d08641c33ff199b75ddd97bde439ce3c9406433f/fix-intl-php72-bug80310.patch
